### ISSUE TITLE
Inserting into a wrapped/grouped relation

### ISSUE THREAD

**Issue by solnic** [dkubb/axiom#55]
Is this supposed to work and if yes then how a tuple should look like?

**Comment by dkubb** [comment]
Sorry for taking so long to answer this.

You can insert into a relation, but you can't insert into a nested relation. You _conceptually_ unwrap/ungroup the relation, perform the insertion, then wrap/group it back. (Although you can insert a tuple into a relation with a nested attribute though)

I say conceptually because that's the brute force method, specifically what would occur in the in-memory adapter. In reality different dbs may provide ways to do this without needing to go through this work. Also it should be possible for the optimizer to rearrange the operations so the work is minimized.

One of the reasons for this restriction, which originally comes from Tutorial D, is that we don't want to duplicate all the core operations for nested relations. That's 3x the number of ops, not even counting if you have to make extra ops for every N level of nesting, even if you could somehow make the ops work multi-level, the apis would become clumsy.

**Comment by solnic** [comment]
Thanks for explaining this!
